import {
  Box,
  Center,
  Flex,
  Heading,
  Text,
  useBreakpointValue,
} from '@chakra-ui/react'
import Head from 'next/head'
import { useModularLayout } from '../hooks'

export default function Home() {
  const isRenderWrapper = useBreakpointValue({
    base: false,
    md: true,
  }) as boolean
  const {
    ModularConditionalWrapper,
    ModularButton,
    ModularParent,
    ModularChild,
    ModularTabs,
    ModularTab,
    ModularTabList,
    ModularTabPanels,
    ModularTabPanel,
    whiteAlphaBg,
    borderRadius,
  } = useModularLayout({ isRenderWrapper })

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ModularParent bg="teal">
        <ModularConditionalWrapper>
          <ModularChild showBorder blackAlphaBg>
            <Heading>This is a heading</Heading>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam
            venenatis at lorem dignissim vulputate. Praesent interdum leo augue,
            in gravida augue mollis ut. Nulla in risus efficitur metus aliquet
            convallis malesuada sed ex. Pellentesque condimentum orci vitae
            venenatis mattis. Vivamus faucibus pharetra leo, vestibulum
            scelerisque orci porta ut. Ut non consectetur quam. Nunc quis
            fringilla libero, vitae pulvinar sem. Vestibulum quis ultrices leo,
            eu posuere enim. Etiam non lacus vitae risus venenatis gravida.
            Nulla eu odio id turpis dapibus iaculis. Curabitur at sagittis
            neque. Quisque luctus porta dapibus. Maecenas sit amet fermentum
            nunc, at fringilla sem. Aenean placerat volutpat dictum. In finibus
            fringilla consequat. Vivamus sapien orci, dignissim in laoreet in,
            hendrerit quis ante. Proin ut interdum velit. Etiam vel orci eros.
            Curabitur massa justo, euismod ac felis eu, pretium suscipit sem.
            Sed commodo luctus elit. Suspendisse feugiat, urna ac fermentum
            scelerisque, justo magna luctus nisl, ut molestie turpis turpis.
          </ModularChild>
          <ModularChild>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam
            venenatis at lorem dignissim vulputate. Praesent interdum leo augue,
            in gravida augue mollis ut. Nulla in risus efficitur metus aliquet
            convallis malesuada sed ex. Pellentesque condimentum orci vitae
            venenatis mattis. Vivamus faucibus pharetra leo, vestibulum
            scelerisque orci porta ut. Ut non consectetur quam. Nunc quis
            fringilla libero, vitae pulvinar sem. Vestibulum quis ultrices leo,
            eu posuere enim. Etiam non lacus vitae risus venenatis gravida.
            Nulla eu odio id turpis dapibus iaculis. Curabitur at sagittis
            neque. Quisque luctus porta dapibus. Maecenas sit amet fermentum
            nunc, at fringilla sem. Aenean placerat volutpat dictum. In finibus
            fringilla consequat. Vivamus sapien orci, dignissim in laoreet in,
            hendrerit quis ante. Proin ut interdum velit. Etiam vel orci eros.
            Curabitur massa justo, euismod ac felis eu, pretium suscipit sem.
            Sed commodo luctus elit. Suspendisse feugiat, urna ac fermentum
            scelerisque, justo magna luctus nisl, ut molestie turpis turpis.
          </ModularChild>
          <ModularChild>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam
            venenatis at lorem dignissim vulputate. Praesent interdum leo augue,
            in gravida augue mollis ut. Nulla in risus efficitur metus aliquet
            convallis malesuada sed ex. Pellentesque condimentum orci vitae
            venenatis mattis. Vivamus faucibus pharetra leo, vestibulum
            scelerisque orci porta ut. Ut non consectetur quam. Nunc quis
            fringilla libero, vitae pulvinar sem. Vestibulum quis ultrices leo,
            eu posuere enim. Etiam non lacus vitae risus venenatis gravida.
            Nulla eu odio id turpis dapibus iaculis. Curabitur at sagittis
            neque. Quisque luctus porta dapibus. Maecenas sit amet fermentum
            nunc, at fringilla sem. Aenean placerat volutpat dictum. In finibus
            fringilla consequat. Vivamus sapien orci, dignissim in laoreet in,
            hendrerit quis ante. Proin ut interdum velit. Etiam vel orci eros.
            Curabitur massa justo, euismod ac felis eu, pretium suscipit sem.
            Sed commodo luctus elit. Suspendisse feugiat, urna ac fermentum
            scelerisque, justo magna luctus nisl, ut molestie turpis turpis.
          </ModularChild>
          <ModularChild>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam
            venenatis at lorem dignissim vulputate. Praesent interdum leo augue,
            in gravida augue mollis ut. Nulla in risus efficitur metus aliquet
            convallis malesuada sed ex. Pellentesque condimentum orci vitae
            venenatis mattis. Vivamus faucibus pharetra leo, vestibulum
            scelerisque orci porta ut. Ut non consectetur quam. Nunc quis
            fringilla libero, vitae pulvinar sem. Vestibulum quis ultrices leo,
            eu posuere enim. Etiam non lacus vitae risus venenatis gravida.
            Nulla eu odio id turpis dapibus iaculis. Curabitur at sagittis
            neque. Quisque luctus porta dapibus. Maecenas sit amet fermentum
            nunc, at fringilla sem. Aenean placerat volutpat dictum. In finibus
            fringilla consequat. Vivamus sapien orci, dignissim in laoreet in,
            hendrerit quis ante. Proin ut interdum velit. Etiam vel orci eros.
            Curabitur massa justo, euismod ac felis eu, pretium suscipit sem.
            Sed commodo luctus elit. Suspendisse feugiat, urna ac fermentum
            scelerisque, justo magna luctus nisl, ut molestie turpis turpis.
          </ModularChild>
        </ModularConditionalWrapper>
        <ModularConditionalWrapper>
          <ModularChild>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam
            venenatis at lorem dignissim vulputate. Praesent interdum leo augue,
            in gravida augue mollis ut. Nulla in risus efficitur metus aliquet
            convallis malesuada sed ex. Pellentesque condimentum orci vitae
            venenatis mattis. Vivamus faucibus pharetra leo, vestibulum
            scelerisque orci porta ut. Ut non consectetur quam. Nunc quis
            fringilla libero, vitae pulvinar sem. Vestibulum quis ultrices leo,
            eu posuere enim. Etiam non lacus vitae risus venenatis gravida.
            Nulla eu odio id turpis dapibus iaculis. Curabitur at sagittis
            neque. Quisque luctus porta dapibus. Maecenas sit amet fermentum
            nunc, at fringilla sem. Aenean placerat volutpat dictum. In finibus
            fringilla consequat. Vivamus sapien orci, dignissim in laoreet in,
            hendrerit quis ante. Proin ut interdum velit. Etiam vel orci eros.
            Curabitur massa justo, euismod ac felis eu, pretium suscipit sem.
            Sed commodo luctus elit. Suspendisse feugiat, urna ac fermentum
            scelerisque, justo magna luctus nisl, ut molestie turpis turpis.
          </ModularChild>
          <ModularChild showBorder blackAlphaBg bg="purple">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam
            venenatis at lorem dignissim vulputate. Praesent interdum leo augue,
            in gravida augue mollis ut. Nulla in risus efficitur metus aliquet
            convallis malesuada sed ex. Pellentesque condimentum orci vitae
            venenatis mattis. Vivamus faucibus pharetra leo, vestibulum
            scelerisque orci porta ut. Ut non consectetur quam. Nunc quis
            fringilla libero, vitae pulvinar sem. Vestibulum quis ultrices leo,
            eu posuere enim. Etiam non lacus vitae risus venenatis gravida.
            Nulla eu odio id turpis dapibus iaculis. Curabitur at sagittis
            neque. Quisque luctus porta dapibus. Maecenas sit amet fermentum
            nunc, at fringilla sem. Aenean placerat volutpat dictum. In finibus
            fringilla consequat. Vivamus sapien orci, dignissim in laoreet in,
            hendrerit quis ante. Proin ut interdum velit. Etiam vel orci eros.
            Curabitur massa justo, euismod ac felis eu, pretium suscipit sem.
            Sed commodo luctus elit. Suspendisse feugiat, urna ac fermentum
            scelerisque, justo magna luctus nisl, ut molestie turpis turpis.
          </ModularChild>
          <ModularChild>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam
            venenatis at lorem dignissim vulputate. Praesent interdum leo augue,
            in gravida augue mollis ut. Nulla in risus efficitur metus aliquet
            convallis malesuada sed ex. Pellentesque condimentum orci vitae
            venenatis mattis. Vivamus faucibus pharetra leo, vestibulum
            scelerisque orci porta ut. Ut non consectetur quam. Nunc quis
            fringilla libero, vitae pulvinar sem. Vestibulum quis ultrices leo,
            eu posuere enim. Etiam non lacus vitae risus venenatis gravida.
            Nulla eu odio id turpis dapibus iaculis. Curabitur at sagittis
            neque. Quisque luctus porta dapibus. Maecenas sit amet fermentum
            nunc, at fringilla sem. Aenean placerat volutpat dictum. In finibus
            fringilla consequat. Vivamus sapien orci, dignissim in laoreet in,
            hendrerit quis ante. Proin ut interdum velit. Etiam vel orci eros.
            Curabitur massa justo, euismod ac felis eu, pretium suscipit sem.
            Sed commodo luctus elit. Suspendisse feugiat, urna ac fermentum
            scelerisque, justo magna luctus nisl, ut molestie turpis turpis.
          </ModularChild>
          <ModularChild bg="gray.600">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam
            venenatis at lorem dignissim vulputate. Praesent interdum leo augue,
            in gravida augue mollis ut. Nulla in risus efficitur metus aliquet
            convallis malesuada sed ex. Pellentesque condimentum orci vitae
            venenatis mattis. Vivamus faucibus pharetra leo, vestibulum
            scelerisque orci porta ut. Ut non consectetur quam. Nunc quis
            fringilla libero, vitae pulvinar sem. Vestibulum quis ultrices leo,
            eu posuere enim. Etiam non lacus vitae risus venenatis gravida.
            Nulla eu odio id turpis dapibus iaculis. Curabitur at sagittis
            neque. Quisque luctus porta dapibus. Maecenas sit amet fermentum
            nunc, at fringilla sem. Aenean placerat volutpat dictum. In finibus
            fringilla consequat. Vivamus sapien orci, dignissim in laoreet in,
            hendrerit quis ante. Proin ut interdum velit. Etiam vel orci eros.
            Curabitur massa justo, euismod ac felis eu, pretium suscipit sem.
            Sed commodo luctus elit. Suspendisse feugiat, urna ac fermentum
            scelerisque, justo magna luctus nisl, ut molestie turpis turpis.
          </ModularChild>
        </ModularConditionalWrapper>
      </ModularParent>
    </>
  )
}
